Update consul and add healthcheck

diff --git a/vendor/github.com/hashicorp/consul/GNUmakefile b/vendor/github.com/hashicorp/consul/GNUmakefile
--- a/vendor/github.com/hashicorp/consul/GNUmakefile
+++ b/vendor/github.com/hashicorp/consul/GNUmakefile
@@ -1,14 +1,24 @@
 SHELL = bash
 GOTOOLS = \
 	github.com/elazarl/go-bindata-assetfs/... \
-	github.com/jteeuwen/go-bindata/... \
+	github.com/hashicorp/go-bindata/... \
+	github.com/magiconair/vendorfmt/cmd/vendorfmt \
 	github.com/mitchellh/gox \
 	golang.org/x/tools/cmd/cover \
-	golang.org/x/tools/cmd/stringer
-GOTAGS ?= consul
+	golang.org/x/tools/cmd/stringer \
+	github.com/axw/gocov/gocov \
+	gopkg.in/matm/v1/gocov-html
+
+GOTAGS ?=
 GOFILES ?= $(shell go list ./... | grep -v /vendor/)
+ifeq ($(origin GOTEST_PKGS_EXCLUDE), undefined)
+GOTEST_PKGS ?= "./..."
+else
+GOTEST_PKGS=$(shell go list ./... | sed 's/github.com\/hashicorp\/consul/./' | egrep -v "^($(GOTEST_PKGS_EXCLUDE))$$")
+endif
 GOOS=$(shell go env GOOS)
 GOARCH=$(shell go env GOARCH)
+GOPATH=$(shell go env GOPATH)
 
 # Get the git commit
 GIT_COMMIT=$(shell git rev-parse --short HEAD)
@@ -27,13 +37,25 @@ bin: tools
 	@GOTAGS='$(GOTAGS)' sh -c "'$(CURDIR)/scripts/build.sh'"
 
 # dev creates binaries for testing locally - these are put into ./bin and $GOPATH
-dev:
+dev: changelogfmt vendorfmt dev-build
+
+dev-build:
+	@echo "--> Building consul"
 	mkdir -p pkg/$(GOOS)_$(GOARCH)/ bin/
 	go install -ldflags '$(GOLDFLAGS)' -tags '$(GOTAGS)'
 	cp $(GOPATH)/bin/consul bin/
 	cp $(GOPATH)/bin/consul pkg/$(GOOS)_$(GOARCH)
 
-# linux builds a linux package indpendent of the source platform
+vendorfmt:
+	@echo "--> Formatting vendor/vendor.json"
+	test -x $(GOPATH)/bin/vendorfmt || go get -u github.com/magiconair/vendorfmt/cmd/vendorfmt
+	vendorfmt
+
+changelogfmt:
+	@echo "--> Making [GH-xxxx] references clickable..."
+	@sed -E 's|([^\[])\[GH-([0-9]+)\]|\1[[GH-\2](https://github.com/hashicorp/consul/issues/\2)]|g' CHANGELOG.md > changelog.tmp && mv changelog.tmp CHANGELOG.md
+
+# linux builds a linux package independent of the source platform
 linux:
 	mkdir -p pkg/linux_amd64/
 	GOOS=linux GOARCH=amd64 go build -ldflags '$(GOLDFLAGS)' -tags '$(GOTAGS)' -o pkg/linux_amd64/consul
@@ -46,17 +68,32 @@ cov:
 	gocov test $(GOFILES) | gocov-html > /tmp/coverage.html
 	open /tmp/coverage.html
 
-test: dev
-	go test -tags "$(GOTAGS)" -i ./...
-	go test -tags "$(GOTAGS)" -run '^$$' ./... > /dev/null
-	go test -tags "$(GOTAGS)" -v $$(go list ./... | egrep -v '(agent/consul|vendor)') > test.log 2>&1 || echo 'FAIL_TOKEN' >> test.log
-	go test -tags "$(GOTAGS)" -v $$(go list ./... | egrep '(agent/consul)') >> test.log 2>&1 || echo 'FAIL_TOKEN' >> test.log
-	@if [ "$$TRAVIS" == "true" ] ; then cat test.log ; fi
-	@if grep -q 'FAIL_TOKEN' test.log ; then grep 'FAIL:' test.log ; exit 1 ; else echo 'PASS' ; fi
+test: other-consul dev-build vet
+	@echo "--> Running go test"
+	@rm -f test.log exit-code
+	go test -tags '$(GOTAGS)' -i $(GOTEST_PKGS)
+	@# Dump verbose output to test.log so we can surface test names on failure but
+	@# hide it from travis as it exceeds their log limits and causes job to be
+	@# terminated (over 4MB and over 10k lines in the UI). We need to output
+	@# _something_ to stop them terminating us due to inactivity...
+	{ go test $(GOTEST_FLAGS) -tags '$(GOTAGS)' -timeout 5m $(GOTEST_PKGS) 2>&1 ; echo $$? > exit-code ; } | tee test.log | egrep '^(ok|FAIL)\s*github.com/hashicorp/consul'
+	@echo "Exit code: $$(cat exit-code)" >> test.log
+	@grep -A5 'DATA RACE' test.log || true
+	@grep -A10 'panic: test timed out' test.log || true
+	@grep -A1 -- '--- SKIP:' test.log || true
+	@grep -A1 -- '--- FAIL:' test.log || true
+	@grep '^FAIL' test.log || true
+	@if [ "$$(cat exit-code)" == "0" ] ; then echo "PASS" ; exit 0 ; else exit 1 ; fi
 
-test-race: dev
-	go test -tags "$(GOTAGS)" -i -run '^$$' ./...
-	( set -o pipefail ; go test -race -tags "$(GOTAGS)" -v ./... 2>&1 | tee test-race.log )
+test-race:
+	$(MAKE) GOTEST_FLAGS=-race
+
+other-consul:
+	@echo "--> Checking for other consul instances"
+	@if ps -ef | grep 'consul agent' | grep -v grep ; then \
+		echo "Found other running consul agents. This may affect your tests." ; \
+		exit 1 ; \
+	fi
 
 cover:
 	go test $(GOFILES) --cover
@@ -67,7 +104,7 @@ format:
 
 vet:
 	@echo "--> Running go vet"
-	@go vet $(GOFILES); if [ $$? -eq 1 ]; then \
+	@go vet -tags '$(GOTAGS)' $(GOFILES); if [ $$? -eq 1 ]; then \
 		echo ""; \
 		echo "Vet found suspicious constructs. Please check the reported constructs"; \
 		echo "and fix them if necessary before submitting the code for review."; \
@@ -84,11 +121,10 @@ ui:
 # also run as part of the release build script when it verifies that there are no
 # changes to the UI assets that aren't checked in.
 static-assets:
-	@go-bindata-assetfs -pkg agent -prefix pkg ./pkg/web_ui/...
-	@mv bindata_assetfs.go agent/
+	@go-bindata-assetfs -pkg agent -prefix pkg -o agent/bindata_assetfs.go ./pkg/web_ui/...
 	$(MAKE) format
 
 tools:
 	go get -u -v $(GOTOOLS)
 
-.PHONY: all ci bin dev dist cov test cover format vet ui static-assets tools
+.PHONY: all ci bin dev dist cov test cover format vet ui static-assets tools vendorfmt
